<?xml version="1.0"?>
<robot
  xmlns:xacro="http://ros.org/wiki/xacro"
  xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
  xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
  xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
  name="velodyne">
  
  <xacro:property name="M_PI" value="3.14159265359"/>
  <xacro:property name="height" value="3.14159265359"/>
  <xacro:property name="diameter" value="0.1095"/>
  <xacro:property name="radius" value="${diameter/2}" />
   
  <link name="base_footprint"/>
  <link name="base_link">
    <visual>
      <origin xyz="${-diameter} ${radius - 0.0039} 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <mesh filename="package://velodyne_description/meshes/velodyne_puck.stl" scale="0.025 0.025 0.025"/>
      </geometry>
      <material name="silver" >
        <color rgba="0.5 0.5 0.5 1" />
      </material>
    </visual>
  </link>
  
  <joint name="velodyne_link_to_base_link" type="fixed">
    <!-- origin xyz="0 0 0.2" rpy="0 ${-M_PI/18.0} 0" /-->
    <origin xyz="0 0 0" rpy="0 0 ${M_PI}" />
    <parent link="base_footprint"/>
    <child link="base_link" />
  </joint>

</robot>
